name: db_commons
description: data base to handle app memory
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
 
dev_dependencies:
  very_good_analysis: ^3.1.0
